project:
  type: website

website:
  title: "MicrobiomeProject"
  navbar:
    left:
      - href: index.qmd
        text: ProjectHub
      - about.qmd

format:
  html:
    theme:
      - flatly
      - brand
    css: style.css
    toc: true



