project:
  type: websit
website:
  navbar:
    left:
      - href: index.qmd
        text: ProjectHub
      - href: overview.qmd
        text: Overview

format:
  html:
    theme:
      - flatly
      - brand
    toc: true
    include-in-header: _includes/header.html






