project:
  type: website
website:
  navbar:
    left:
      - href: index.qmd
        text: MicrobiomeProjectHub
      - href: overview.qmd
        text: Overview
      - href : projects.qmd
        text : Projects
      - href : commit_log.qmd
        text : CommitLog

format:
  html:
    theme:
      - flatly
      - brand
    css: style.css
    toc: true
    






